<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>EnterpriseAiPlatform.ModelRegistry.UnitTests</RootNamespace>
    <AssemblyName>EnterpriseAiPlatform.ModelRegistry.UnitTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Services\ModelRegistry\EnterpriseAiPlatform.ModelRegistry.Application\EnterpriseAiPlatform.ModelRegistry.Application.csproj" />
    <ProjectReference Include="..\..\src\Services\ModelRegistry\EnterpriseAiPlatform.ModelRegistry.Contracts\EnterpriseAiPlatform.ModelRegistry.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Services\ModelRegistry\EnterpriseAiPlatform.ModelRegistry.Domain\EnterpriseAiPlatform.ModelRegistry.Domain.csproj" />
    <ProjectReference Include="..\..\src\Services\ModelRegistry\EnterpriseAiPlatform.ModelRegistry.Infrastructure\EnterpriseAiPlatform.ModelRegistry.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\EnterpriseAiPlatform.Application.Abstractions\EnterpriseAiPlatform.Application.Abstractions.csproj" />
  </ItemGroup>

</Project>
