<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\EnterpriseAiPlatform.Audit.Application\EnterpriseAiPlatform.Audit.Application.csproj" />
    <ProjectReference Include="..\EnterpriseAiPlatform.Audit.Domain\EnterpriseAiPlatform.Audit.Domain.csproj" />
    <ProjectReference Include="..\EnterpriseAiPlatform.Audit.Contracts\EnterpriseAiPlatform.Audit.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnterpriseAiPlatform.Infrastructure.Abstractions\EnterpriseAiPlatform.Infrastructure.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
