<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\EnterpriseAiPlatform.Metering.Application\EnterpriseAiPlatform.Metering.Application.csproj" />
    <ProjectReference Include="..\EnterpriseAiPlatform.Metering.Infrastructure\EnterpriseAiPlatform.Metering.Infrastructure.csproj" />
    <ProjectReference Include="..\EnterpriseAiPlatform.Metering.Contracts\EnterpriseAiPlatform.Metering.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnterpriseAiPlatform.ServiceDefaults\EnterpriseAiPlatform.ServiceDefaults.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
