<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EnterpriseAiPlatform.ProviderAdapters.Domain\EnterpriseAiPlatform.ProviderAdapters.Domain.csproj" />
    <ProjectReference Include="..\EnterpriseAiPlatform.ProviderAdapters.Contracts\EnterpriseAiPlatform.ProviderAdapters.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnterpriseAiPlatform.Application.Abstractions\EnterpriseAiPlatform.Application.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>EnterpriseAiPlatform.ProviderAdapters.Application</RootNamespace>
    <AssemblyName>EnterpriseAiPlatform.ProviderAdapters.Application</AssemblyName>
  </PropertyGroup>

</Project>
