<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\EnterpriseAiPlatform.Application.Abstractions\EnterpriseAiPlatform.Application.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnterpriseAiPlatform.ServiceDefaults\EnterpriseAiPlatform.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\ModelRegistry\EnterpriseAiPlatform.ModelRegistry.Infrastructure\EnterpriseAiPlatform.ModelRegistry.Infrastructure.csproj" />
    <ProjectReference Include="..\..\LocalModel\EnterpriseAiPlatform.LocalModel.Infrastructure\EnterpriseAiPlatform.LocalModel.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
